# GDELT Data Analysis

## Objectif

1/ Afficher le nombre d’articles/évènements qu’il y a eu pour chaque triplet (jour, pays de l’évènement, langue de l’article).

2/ Pour un pays donné en paramètre, affichez les évènements qui y ont eu place triées par le nombre de mentions (tri décroissant); permettez une agrégation par jour/mois/année

3/ Pour une source de donnés passée en paramètre (gkg.SourceCommonName) affichez les thèmes, personnes, lieux dont les articles de cette sources parlent ainsi que le nombre d’articles et le ton moyen des articles (pour chaque thème/personne/lieu); permettez une agrégation par jour/mois/année.

4/ étudiez l’évolution des relations entre deux pays (specifies en paramètre) au cours de l’année. Vous pouvez vous baser sur la langue de l’article, le ton moyen des articles, les themes plus souvent citées, les personalités ou tout element qui vous semble pertinent.

### Import libraries

In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 100
# pd.options.display.max_rows = 4000

## Table export.csv

In [2]:
export = pd.read_csv("data_sample/20150218230000.export.CSV", sep="\t", header = None)
export

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60
0,410412347,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GOV,PRESIDENT,NaN,NaN,NaN,NaN,NaN,GOV,NaN,NaN,0,43,43,4,1,2.8,5,1,5,-4.477612,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Waterkloof, Free State, South Africa",SF,SF03,77359,-30.3098,25.2971,-1299321,4,"Waterkloof, Free State, South Africa",SF,SF03,77359,-30.3098,25.2971,-1299321,20150218230000,http://www.dailymaverick.co.za/article/2015-02...
1,410412348,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IND,MUMBAI,IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,42,42,4,1,1.9,5,1,5,2.078522,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Mumbai, Maharashtra, India",IN,IN16,70184,18.9750,72.8258,-2092174,4,"Bengaluru, Karnataka, India",IN,IN19,70159,12.9833,77.5833,-2090174,20150218230000,http://timesofindia.indiatimes.com/city/bengal...
2,410412349,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NZL,KIWI,NZL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,42,42,4,1,1.9,1,1,1,7.517084,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,New Zealand,NZ,NZ,NaN,-41.0000,174.0000,NZ,4,"Great Southern, Victoria, Australia",AS,AS07,5387,-36.0667,146.4830,-1576477,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
3,410412350,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NZL,KIWI,NZL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,42,42,4,1,1.9,2,1,2,7.517084,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,New Zealand,NZ,NZ,NaN,-41.0000,174.0000,NZ,1,New Zealand,NZ,NZ,NaN,-41.0000,174.0000,NZ,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
4,410412351,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA,LOS ANGELES,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,42,42,4,1,1.9,10,1,10,0.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"Idaho, United States",US,USID,NaN,44.2394,-114.5100,ID,2,"Idaho, United States",US,USID,NaN,44.2394,-114.5100,ID,20150218230000,http://www.eastidahonews.com/2015/02/neil-patr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,410414613,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,40,40,4,1,1.0,6,1,6,-3.703704,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2267,410414614,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,46,46,4,1,7.0,6,1,6,-3.703704,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2268,410414615,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,NaN,NaN,NaN,NaN,NaN,PAK,PAKISTAN,PAK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,40,40,4,1,1.0,2,1,2,-3.703704,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2269,410414616,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,NaN,NaN,NaN,NaN,NaN,PAK,PAKISTAN,PAK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,46,46,4,1,7.0,2,1,2,-3.703704,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,4,"Mohin-Jo-Daro, Sindh, Pakistan",PK,PK05,23687,27.3287,68.1325,-2769374,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2270,410414617,20150218,201502,2015,2015.1315,tib,TIBETAN,NaN,NaN,tib,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,10,1,1,0.0,10,1,10,-0.411523,4,"Amdo, Xizang, China",CH,CH14,13213,32.3333,91.6667,-1920650,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Amdo, Xizang, China",CH,CH14,13213,32.3333,91.6667,-1920650,20150218230000,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...

## Table menstions.csv

In [3]:
mentions = pd.read_csv("data_sample/20150218230000.mentions.CSV", sep="\t", header=None)
mentions

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,410412347,20150218230000,20150218230000,1,dailymaverick.co.za,http://www.dailymaverick.co.za/article/2015-02...,19,-1,4594,4634,1,50,6665,-4.477612,NaN,NaN
1,410412348,20150218230000,20150218230000,1,indiatimes.com,http://timesofindia.indiatimes.com/city/bengal...,2,-1,300,344,1,50,2541,2.078522,NaN,NaN
2,410412349,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1297,1232,0,10,2576,7.517084,NaN,NaN
3,410412350,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1298,1233,1,20,2576,7.517084,NaN,NaN
4,410412351,20150218230000,20150218230000,1,eastidahonews.com,http://www.eastidahonews.com/2015/02/neil-patr...,1,-1,103,122,1,100,1432,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8457,410414615,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,442,0,20,1994,-3.703704,NaN,NaN
8458,410414616,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,367,0,20,1994,-3.703704,NaN,NaN
8459,410232648,20150218100000,20150218230000,1,suttonguardian.co.uk,http://www.suttonguardian.co.uk/news/national/...,6,1870,-1,1803,1,100,5040,-0.738916,NaN,NaN
8460,410339294,20150218171500,20150218230000,1,edgeboston.com,http://www.edgeboston.com/entertainment/celebr...,2,454,-1,411,1,50,858,6.250000,NaN,NaN
8461,410414617,20150218230000,20150218230000,1,bbg.gov,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...,1,318,-1,345,1,100,1584,-0.411523,NaN,NaN

In [4]:
for i in range(mentions.shape[1]):
    print(mentions.iloc[45,i])

410412367
20150218230000
20150218230000
1
dailymaverick.co.za
http://www.dailymaverick.co.za/article/2015-02-19-sona2015-jamming-state-security-agency-steps-forward-blames-low-ranking-operator/
19
4594
-1
4634
0
20
6665
-4.4776119402985
nan
nan

## Table gkg.csv

In [5]:
gkg = pd.read_csv("data_sample/20150218230000.gkg.csv", sep="\t", header=None)
gkg

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
0,20150218230000-0,20150218230000,2,BBC Monitoring,as listed in Russian /BBC Monitoring/(c) BBC,"ARREST#400#political#4#Rossiya, Orenburgskaya ...","ARREST#400#political#4#Rossiya, Orenburgskaya ...",TERROR;REBELS;TAX_ETHNICITY;TAX_ETHNICITY_UKRA...,"TAX_FNCACT,2011;TAX_FNCACT,3449;TAX_FNCACT,381...","4#Budapest, Budapest, Hungary#RS#HU05#47.5#19....","4#Novorossiya, Primorskiy Kray, Russia#RS#RS59...",petro poroshenko;arkadiy dvorkovich;gen aleksa...,"Petro Poroshenko,2326;Arkadiy Dvorkovich,3483;...",gazprom,"Gazprom,666","-5.3475935828877,2.13903743315508,7.4866310160...",NaN,"wc:693,c1.1:1,c1.2:1,c12.1:43,c12.10:58,c12.11...",NaN,NaN,NaN,NaN,1332|134||prisoners are treated humanely ; the...,"Channel One,628;Channel One,755;Channel One,14...","3,channels,476;3,channels reported,824;1,corre...",NaN,NaN
1,20150218230000-1,20150218230000,2,BBC Monitoring,"Al-Sharq al-Awsat website, London/BBC Monitori...",NaN,NaN,TAX_FNCACT;TAX_FNCACT_ENVOY;TAX_ETHNICITY;TAX_...,"IDEOLOGY,6790;IDEOLOGY,10592;KILL,1960;KILL,13...",1#Qatar#SA#QA#25.5#51.25#QA;1#Syria#SA#SY#35#3...,1#Turks#SA#TU##39#35#TU#9059;1#Syrian#SA#SY##3...,al-arab kobane;emrullah isler;nasirite alawite...,"Al-Arab Kobane,4903;Emrullah Isler,77;Nasirite...",development party;united states,"Development Party,3577;Development Party,3746;...","-0.54054054054054,3.82239382239382,4.362934362...",NaN,"wc:2376,c1.2:1,c1.4:7,c12.1:163,c12.10:276,c12...",NaN,NaN,NaN,NaN,332|26||greatly complicate matters#4494|37||ma...,"Emrullah Isler,83;Arab Spring,3571;Development...","2,fronts at the political,1455;2,main strategi...",NaN,NaN
2,20150218230000-2,20150218230000,1,wjon.com,http://wjon.com/wjon-news-on-demand-wednesday-...,NaN,NaN,MANMADE_DISASTER;MANMADE_DISASTER_WITHOUT_POWE...,"MANMADE_DISASTER,91;POWER_OUTAGE,91;",NaN,NaN,NaN,NaN,NaN,NaN,"0,0,0,0,29.7029702970297,0.99009900990099,93",NaN,"wc:93,c12.1:7,c12.10:10,c12.12:5,c12.13:4,c12....",http://wac.450F.edgecastcdn.net/80450F/wjon.co...,http:/wac.450F.edgecastcdn.net/80450F/wjon.com...,NaN,https://youtube.com/channel/;https://youtube.c...,NaN,"Waite Park,125;City Food,233;Adobe Flash Playe...","500,people were without power,51;",NaN,NaN
3,20150218230000-3,20150218230000,1,wjol.com,http://www.wjol.com/common/more.php?m=15&r=3&i...,NaN,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_GOVERNOR;TAX_POLI...,"TAX_FNCACT,131;TAX_POLITICAL_PARTY,664;TAX_FNC...","2#Wisconsin, United States#US#USWI#44.2563#-89...","2#Wisconsin, United States#US#USWI##44.2563#-8...",michael madigan;rahm emanuel;jesus chuy garcia,"Michael Madigan,147;Rahm Emanuel,313;Jesus Chu...",NaN,NaN,"-4.58715596330275,1.8348623853211,6.4220183486...",NaN,"wc:103,c12.1:4,c12.10:13,c12.12:7,c12.13:6,c12...",NaN,NaN,NaN,NaN,NaN,"Governor Rauner,41;Speaker Michael Madigan,158...",NaN,NaN,NaN
4,20150218230000-4,20150218230000,1,straitstimes.com,http://www.straitstimes.com:80/news/world/unit...,NaN,NaN,DRONES;TAX_WORLDMAMMALS;TAX_WORLDMAMMALS_MICE;...,"TAX_FNCACT,634;TAX_FNCACT,1248;TAX_FNCACT,907;...","1#United States#US#US#38#-97#US;3#Miami, Flori...","3#Miami, Florida, United States#US#USFL#FL086#...",omid farokhzad,"Omid Farokhzad,885",columbia university medical centre;harvard med...,"Columbia University Medical Centre,680;Harvard...","-1.80505415162455,3.6101083032491,5.4151624548...",4#2#18#0#706,"wc:255,c12.1:10,c12.10:28,c12.12:11,c12.13:7,c...",http://www.straitstimes.com/sites/straitstimes...,NaN,NaN,NaN,NaN,"United States,583;Columbia University Medical ...","5,weeks,1194;",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,20150218230000-203,20150218230000,1,theaustralian.com.au,http://www.theaustralian.com.au/business/finan...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_CHIEF;TAX_FNCACT_EXECUTI...,"TAX_FNCACT,552;TAX_ETHNICITY,1171;TAX_ETHNICIT...",1#Australia#AS#AS#-27#133#AS,1#Australian#AS#AS##-27#133#AS#1171;1#Australi...,craig meller,"Craig Meller,575",NaN,NaN,"6.06060606060606,6.06060606060606,0,6.06060606...",4#12#31#0#17;4#4#10#0#253;4#3#3#0#297;1#0#0#20...,"wc:300,c1.2:7,c12.1:8,c12.10:23,c12.12:3,c12.1...",http://resources.news.com.au/cs/theaustralian/...,NaN,NaN,NaN,NaN,"Craig Meller,647;Dow Jones,1941","884000000,dollars ,65;672000000,dollars result...",NaN,NaN
3184,20150218230000-204,20150218230000,1,yahoo.com,http://finance.yahoo.com/news/chg-healthcare-s...,NaN,NaN,MEDICAL;TAX_WORLDLANGUAGES;TAX_WORLDLANGUAGES_...,"GENERAL_HEALTH,1512;TAX_FNCACT,1339;TAX_FNCACT...",1#United States#US#US#38#-97#US,1#America#US#US##38#-97#US#632;1#America#US#US...,scott beck,"Scott Beck,945",foundation medical staffing;healthcare services,"Foundation Medical Staffing,1521;Healthcare Se...","9.03225806451613,9.03225806451613,0,9.03225806...",4#2#18#0#36;1#0#0#1979#1351,"wc:278,c1.2:4,c12.1:21,c12.10:22,c12.12:4,c12....",http://l2.yimg.com/bt/api/res/1.2/6rik6AZwuPGC...,NaN,NaN,NaN,NaN,"Weatherby Healthcare,219;Staffing Award,378;No...","100,Best Places,1632;5,consecutive years,1656;",NaN,NaN
3185,20150218230000-205,20150218230000,1,france24.com,http://www.france24.com/en/20150218-un-issue-f...,KILL#200##1#Liberia#LI#LI#6.5#-9.5#LI;,KILL#200##1#Liberia#LI#LI#6.5#-9.5#LI#1821;,TAX_DISEASE;TAX_DISEASE_EBOLA;TAX_WORLDFISH;TA...,"GENERAL_HEALTH,1311;MEDICAL,1311;TAX_DISEASE,1...","1#Guinea#LI#GV#11#-10#GV;4#Freetown, Western A...",1#Sierra Leone#LI#SL##8.5#-11.5#SL#179;1#Sierr...,david nabarro;laura taylor-pearce,"David Nabarro,482",united nations,"United Nations,15;United Nations,54;United Nat...","-3.63636363636364,1.81818181818182,5.454545454...",NaN,"wc:307,c12.1:17,c12.10:30,c12.12:12,c12.13:14,...",http://scd.france24.com/en/files/imagecache/fr...,NaN,NaN,NaN,NaN,"United Nations,44;Sierra Leone,175;David Nabar...","3000000,dollars donated,180;31,donors since Se...",NaN,NaN
3186,20150218230000-206,20150218230000,1,rri.ro,http://www.rri.ro/en_gb/RadioRomaniaInternatio...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_AUTHOR;MEDIA_MSM;TAX_FNC...,"TAX_FNCACT,13378;MEDIA_MSM,478;MEDIA_MSM,1389;...",NaN,NaN,categorytype parentcategory,"Categorytype Parentcategory,12207;Categorytype...",group by page,"Group By Page,11360","-0.679941719281204,0,0.679941719281204,0.67994...",NaN,"wc:1695,c12.1:40,c12.10:54,c12.12:15,c12.13:1,...",NaN,NaN,NaN,https://youtube.com/user/EugenCojocariu?featur...,NaN,"History Show,15982;CategoryType ParentCategory...","15,SELECT `Page` `id`,956;15,SELECT `Page` `id...",NaN,NaN
3187,20150218230000-207,20150218230000,1,sfgate.com,http://www.sfgate.com/business/article/Swiss-p...,NaN,NaN,TRIAL;TAX_FNCACT;TAX_FNCACT_PROSECUTORS;DRUG_T...,"TAX_ETHNICITY,1135;TAX_ETHNICITY,1236;TAX_WORL...","4#Geneva, Genè, Switzerland#SZ#SZ07#46.1956#6....",1#French#SZ#FR##46#2#FR#1135;1#French#SZ#FR##4...,herve falciani,"Herve Falciani,1109",bank suisse;international consortium of invest...,"Bank Suisse,296;International Consortium Of In...","-3.40136054421769,0.680272108843537,4.08163265...",1#0#0#2007#1001;1#0#0#2008#1209;1#0#0#2012#156...,"wc:265,c12.1:8,c12.10:11,c12.12:5,c12.13:4,c12...",http://www.sfgate.com/img/pages/article/opengr...,NaN,NaN,NaN,591|29||the recent public revelations,"International Consortium,791;Investigative Jou...","1000000,of dollars for drug,152;1000000,of dol...",NaN,NaN

### On importe les fichiers CSV Translations

In [6]:
export_translation = pd.read_csv("data_sample/20150218230000.translation.export.CSV", sep="\t", header=None)
export_translation

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60
0,410414618,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRM,THIEVES,NaN,NaN,NaN,NaN,NaN,CRM,NaN,NaN,1,40,40,4,1,1.0,4,1,4,-5.576923,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Prague, Praha, Hlavníesto, Czech Republic",EZ,EZ52,14865,50.0833,14.4667,-553173,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,20150218230000,http://www.novinky.cz/krimi/361969-majitele-ga...
1,410414619,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRM,THIEVES,NaN,NaN,NaN,NaN,NaN,CRM,NaN,NaN,1,40,40,4,1,1.0,6,1,6,-5.576923,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Prague, Praha, Hlavníesto, Czech Republic",EZ,EZ52,14865,50.0833,14.4667,-553173,4,"Prague, Praha, Hlavníesto, Czech Republic",EZ,EZ52,14865,50.0833,14.4667,-553173,20150218230000,http://www.novinky.cz/krimi/361969-majitele-ga...
2,410414620,20140218,201402,2014,2014.1315,COP,POLICEMEN,NaN,NaN,NaN,NaN,NaN,COP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,112,112,11,3,-2.0,4,1,4,-5.576923,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,20150218230000,http://www.novinky.cz/krimi/361969-majitele-ga...
3,410414621,20140218,201402,2014,2014.1315,COP,POLICEMEN,NaN,NaN,NaN,NaN,NaN,COP,NaN,NaN,CZE,CZECH REPUBLIC,CZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,112,112,11,3,-2.0,6,1,6,-5.576923,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,4,"Nymburk, Stredoceský, Czech Republic",EZ,EZ88,14864,50.1904,15.0395,-551621,20150218230000,http://www.novinky.cz/krimi/361969-majitele-ga...
4,410414622,20140218,201402,2014,2014.1315,CRM,THIEVES,NaN,NaN,NaN,NaN,NaN,CRM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,40,40,4,1,1.0,10,1,10,-5.576923,4,"Rumburk, Czech Republic (general), Czech Republic",EZ,EZ00,16560,50.9536,14.5538,-554298,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"Rumburk, Czech Republic (general), Czech Republic",EZ,EZ00,16560,50.9536,14.5538,-554298,20150218230000,http://www.novinky.cz/krimi/361969-majitele-ga...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,410415411,20150218,201502,2015,2015.1315,cor,CORNISH,NaN,NaN,cor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,40,40,4,1,1.0,6,1,6,3.157895,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,20150218230000,http://www.vetogate.com/1485717
794,410415412,20150218,201502,2015,2015.1315,cor,CORNISH,NaN,NaN,cor,NaN,NaN,NaN,NaN,NaN,EGY,EGYPT,EGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17,17,1,1,0.0,2,1,2,3.157895,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,20150218230000,http://www.vetogate.com/1485717
795,410415413,20150218,201502,2015,2015.1315,cor,CORNISH,NaN,NaN,cor,NaN,NaN,NaN,NaN,NaN,EGY,EGYPT,EGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,40,40,4,1,1.0,2,1,2,3.157895,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,0,NaN,EG,EG10,NaN,28.1000,30.0000,-290634,20150218230000,http://www.vetogate.com/1485717
796,410415414,20150218,201502,2015,2015.1315,scn,SICILIAN,NaN,NaN,scn,NaN,NaN,NaN,NaN,NaN,ITA,CALABRIA,ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,141,141,14,3,-6.5,8,1,8,2.941176,4,"Palermo, Sicilia, Italy",IT,IT15,18395,38.1167,13.3667,-123798,4,"Palermo, Sicilia, Italy",IT,IT15,18395,38.1167,13.3667,-123798,4,"Palermo, Sicilia, Italy",IT,IT15,18395,38.1167,13.3667,-123798,20150218230000,http://fai.informazione.it/p/55877320-CC20-4F9...
797,410415415,20150218,201502,2015,2015.1315,scn,SICILIAN,NaN,NaN,scn,NaN,NaN,NaN,NaN,NaN,ITA,ITALY,ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,141,141,14,3,-6.5,2,1,2,2.941176,0,NaN,IT,IT14,NaN,40.0000,9.0000,-129004,4,"Palermo, Sicilia, Italy",IT,IT15,18395,38.1167,13.3667,-123798,4,"Palermo, Sicilia, Italy",IT,IT15,18395,38.1167,13.3667,-123798,20150218230000,http://fai.informazione.it/p/55877320-CC20-4F9...

In [7]:
mentions_translation = pd.read_csv("data_sample/20150218230000.translation.mentions.CSV", sep="\t", header=None)
mentions_translation

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,410108590,20150218000000,20150218230000,1,surenio.com.ar,http://www.surenio.com.ar/index.php?s=!notas20...,4,1355,-1,1440,1,100,1653,-0.760456,srclc:spa;eng:GT-SPA 1.0,NaN
1,410414618,20150218230000,20150218230000,1,novinky.cz,http://www.novinky.cz/krimi/361969-majitele-ga...,3,-1,1330,1376,0,40,3254,-5.576923,srclc:ces;eng:GT-CES 1.0,NaN
2,410414619,20150218230000,20150218230000,1,novinky.cz,http://www.novinky.cz/krimi/361969-majitele-ga...,3,-1,1330,1376,1,60,3254,-5.576923,srclc:ces;eng:GT-CES 1.0,NaN
3,410353873,20150218181500,20150218230000,1,bt.no,http://www.bt.no/nyheter/lokalt/--Sokte-pa-dra...,5,-1,445,433,1,100,3254,-6.496063,srclc:nor;eng:GT-NOR 1.0,NaN
4,410414620,20150218230000,20150218230000,1,novinky.cz,http://www.novinky.cz/krimi/361969-majitele-ga...,4,1518,-1,1528,1,40,3254,-5.576923,srclc:ces;eng:GT-CES 1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,410211801,20150218081500,20150218230000,1,fasopresse.net,http://www.fasopresse.net/international/4042-c...,6,1728,1707,1655,0,10,5322,-2.038505,srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2819,410211802,20150218081500,20150218230000,1,fasopresse.net,http://www.fasopresse.net/international/4042-c...,6,1715,1707,1655,1,70,5322,-2.038505,srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2820,410115932,20150218001500,20150218230000,1,fasopresse.net,http://www.fasopresse.net/index.php?start=25&5...,4,614,-1,600,1,100,4202,-1.178203,srclc:fra;eng:GT-FRA 1.0,NaN
2821,410415414,20150218230000,20150218230000,1,fai.informazione.it,http://fai.informazione.it/p/55877320-CC20-4F9...,3,1027,1040,1049,1,80,1819,2.941176,srclc:ita;eng:GT-ITA 1.0,NaN
2822,410415415,20150218230000,20150218230000,1,fai.informazione.it,http://fai.informazione.it/p/55877320-CC20-4F9...,3,1027,1072,1049,0,20,1819,2.941176,srclc:ita;eng:GT-ITA 1.0,NaN

In [8]:
gkg_translation = pd.read_csv("data_sample/20150218230000.translation.gkg.csv", sep="\t", header=None)
gkg_translation

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
0,20150218230000-T0,20150218230000,1,literarky.cz,http://www.literarky.cz/komentare/ostatni/1930...,NaN,NaN,EDUCATION;TAX_FNCACT;TAX_FNCACT_AUTHOR;TAX_FNC...,"TAX_FNCACT,8270;MEDIA_MSM,13973;TAX_WORLDMAMMA...",NaN,NaN,NaN,NaN,NaN,NaN,"-0.27047913446677,2.51159196290572,2.782071097...",1#0#0#2010#14975,"wc:2405,c1.1:3,c1.2:2,c1.3:4,c1.4:7,c12.1:260,...",http://www.literarky.cz/images/2015/ART/Rodin-...,NaN,NaN,https://youtube.com/embed/GXaQrfj-th0;https://...,NaN,"Where Will,1419;Why Do Not,5697;Because There,...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
1,20150218230000-T1,20150218230000,1,parlamentnilisty.cz,http://www.parlamentnilisty.cz/arena/monitor/P...,NaN,NaN,TAX_ETHNICITY;TAX_ETHNICITY_UKRAINIAN;TAX_WORL...,"GENERAL_GOVERNMENT,42;GENERAL_GOVERNMENT,264;G...","1#Russia#UP#RS#60#100#RS;4#Kyiv, Kyyiv, Misto,...",1#Russians#UP#RS##60#100#RS#1858;1#Ukrainian#U...,NaN,NaN,NaN,NaN,"-5.1685393258427,1.12359550561798,6.2921348314...",NaN,"wc:421,c1.3:1,c12.1:33,c12.10:57,c12.12:19,c12...",NaN,NaN,NaN,NaN,NaN,"Debal'tseve Ukrainian Government,44;Army Expla...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2,20150218230000-T2,20150218230000,1,vecernikpv.cz,http://www.vecernikpv.cz/co-se-stalo/zpravodaj...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_CITIZENS;TRAFFIC;TRIAL;L...,"TAX_FNCACT,2280;TRAFFIC,277;TRAFFIC,1264;ARMED...",NaN,NaN,jan nagy;petr kapounek,"Jan Nagy,1919;Petr Kapounek,2380",NaN,NaN,"-3.45528455284553,1.01626016260163,4.471544715...",NaN,"wc:468,c1.3:1,c12.1:33,c12.10:37,c12.12:16,c12...",NaN,http:/www.vecernikpv.cz/media/system/images/li...,NaN,NaN,NaN,"Petition From,428;August Last,1046;Now There,1...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
3,20150218230000-T3,20150218230000,1,parlamentnilisty.cz,http://www.parlamentnilisty.cz/arena/monitor/P...,NaN,NaN,EDUCATION;,"EDUCATION,12;",NaN,NaN,NaN,NaN,university john amos,"University John Amos,188","0.710900473933649,3.55450236966825,2.843601895...",NaN,"wc:403,c12.1:20,c12.10:46,c12.12:16,c12.13:19,...",NaN,http:/cms.parlamentnilisty.cz/image.ashx,NaN,NaN,NaN,"University John Amos,189;Confirmed As Well,513...","2,of its regional branches,1389;200,work,1763;",srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
4,20150218230000-T4,20150218230000,1,novinky.cz,http://www.novinky.cz/koktejl/362005-za-sest-h...,NaN,NaN,KILL;TAX_FNCACT;TAX_FNCACT_EMPLOYER;,"TAX_FNCACT,420;KILL,70;",NaN,NaN,NaN,NaN,gazeta wyborcza,"Gazeta Wyborcza,267","2.63157894736842,7.01754385964912,4.3859649122...",NaN,"wc:98,c12.1:7,c12.10:11,c12.12:3,c12.13:3,c12....",http://media.novinky.cz/592/475922-top_foto1-e...,NaN,NaN,NaN,NaN,"Gazeta Wyborcza,305","20000,clean on hand,194;",srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3104,20150218230000-T220,20150218230000,1,dantri.com.vn,http://dantri.com.vn/blog/bac-ho-voi-tho-xuan-...,AFFECT#3#engineering#0######;KILL#200#Thing n ...,AFFECT#3#engineering#0#######53;KILL#200#Thing...,GENERAL_HEALTH;MEDICAL;HEALTH_VACCINATION;TAX_...,"GENERAL_GOVERNMENT,1618;GENERAL_GOVERNMENT,290...",NaN,NaN,NaN,NaN,international l place;a research;s research;nh...,"International L Place,712;A Research,1553;S Re...","1.4268727705113,4.99405469678954,3.56718192627...",NaN,"wc:836,nwc:869,c1.4:1,c12.1:84,c12.10:99,c12.1...",http://dantri21.vcmedia.vn/pHY2RLD1xoL70pWhyid...,NaN,NaN,NaN,NaN,"Market There,2569;Field Research Main,2593;For...","3,parents first Ch Fertilization,433;3,enginee...",srclc:vie;eng:GT-VIE 1.0,NaN
3105,20150218230000-T221,20150218230000,1,dantri.com.vn,http://dantri.com.vn/blog/bac-ho-voi-tho-xuan-...,NaN,NaN,GENERAL_HEALTH;MEDICAL;WATER_SECURITY;,"WATER_SECURITY,805;WATER_SECURITY,924;GENERAL_...",NaN,NaN,NaN,NaN,society under center,"Society Under Center,68","2.1978021978022,3.2967032967033,1.098901098901...",NaN,"wc:182,nwc:214,c12.1:11,c12.10:31,c12.12:9,c12...",http://dantri21.vcmedia.vn/pHY2RLD1xoL70pWhyid...,NaN,NaN,NaN,NaN,"Society Under Center,69;Northwest Area,516;Nor...",NaN,srclc:vie;eng:GT-VIE 1.0,NaN
3106,20150218230000-T222,20150218230000,1,dantri.com.vn,http://dantri.com.vn/blog/bac-ho-voi-tho-xuan-...,NaN,NaN,TAX_MILITARY_TITLE;TAX_MILITARY_TITLE_OFFICER;...,"TAX_FNCACT,475;TAX_FNCACT,507;EDUCATION,427;MA...",NaN,NaN,NaN,NaN,high school,"High School,427","4.40528634361233,7.26872246696035,2.8634361233...",NaN,"wc:451,nwc:427,c1.1:2,c12.1:50,c12.10:40,c12.1...",http://dantri21.vcmedia.vn/pHY2RLD1xoL70pWhyid...,NaN,NaN,NaN,NaN,"Love Sex Married August,39;January I New,122;R...","40,sister medium I tall,245;30,such,935;3,Mont...",srclc:vie;eng:GT-VIE 1.0,NaN
3107,20150218230000-T223,20150218230000,1,dantri.com.vn,http://dantri.com.vn/blog/bac-ho-voi-tho-xuan-...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_SINGER;TAX_FNCACT_DANCER...,"TAX_FNCACT,698;TAX_FNCACT,852;TAX_FNCACT,893;T...",NaN,NaN,NaN,NaN,permanent provinces committee;central party;pe...,"Permanent Provinces Committee,933;Central Part...","7.57575757575757,8.58585858585858,1.0101010101...",NaN,"wc:197,nwc:222,c1.1:1,c12.1:16,c12.10:11,c12.1...",http://dantri21.vcmedia.vn/pHY2RLD1xoL70pWhyid...,NaN,NaN,NaN,NaN,"Before Place,27;Committee Province,447;Preside...",NaN,srclc:vie;eng:GT-VIE 1.0,NaN
3108,20150218230000-T224,20150218230000,1,dantri.com.vn,http://dantri.com.vn/blog/bac-ho-voi-tho-xuan-...,NaN,NaN,GENERAL_HEALTH;MEDICAL;TAX_FNCACT;TAX_FNCACT_P...,"TAX_ETHNICITY,131;TAX_ETHNICITY,279;TAX_WORLDL...","1#Vietnam, Republic Of#VM#VM#16#106#VM",1#Vietnam#VM#VM##16#106#VM#723;1#Vietnam#VM#VM...,NaN,NaN,NaN,NaN,"3.82978723404255,5.31914893617021,1.4893617021...",NaN,"wc:466,nwc:509,c1.1:14,c12.1:39,c12.10:35,c12....",http://dantri21.vcmedia.vn/pHY2RLD1xoL70pWhyid...,NaN,NaN,NaN,NaN,"Land Sun,116;English Her,284;Tet There,551;Phy...","2,a m system guide,2037;",srclc:vie;eng:GT-VIE 1.0,NaN

## Renommage des colonnes des dataframes

In [9]:
# export
x = 'export_'
for i in range(export.shape[1]):
    export.rename({i: x+str(i)}, axis=1, inplace=True)
    
# mentions
x = 'mentions_'
for i in range(mentions.shape[1]):
    mentions.rename({i: x+str(i)}, axis=1, inplace=True)
    
# gkg
x = 'gkg_'
for i in range(gkg.shape[1]):
    gkg.rename({i: x+str(i)}, axis=1, inplace=True)
    
# gkg_translation
x = 'gkg_translation_'
for i in range(gkg_translation.shape[1]):
    gkg_translation.rename({i: x+str(i)}, axis=1, inplace=True)

# export_translation
x = 'export_translation_'
for i in range(export_translation.shape[1]):
    export_translation.rename({i: x+str(i)}, axis=1, inplace=True)

## Requêtes

#### Nombre d'article par jour

In [10]:
export["export_1"] = pd.to_datetime(export["export_1"], format='%Y%m%d') # column_1 = date
nb_event_per_day = export["export_1"].value_counts()
nb_event_per_day

2015-02-18    2176
2014-02-18      52
2015-02-11      15
2015-02-17      15
2015-01-19      13
Name: export_1, dtype: int64

#### Nombre d'article par pays d'évènement

In [11]:
nb_event_per_country = export["export_53"].value_counts() # 53 = CountryCode
nb_event_per_country

US    838
IR    109
CA     96
LY     91
PK     87
     ...
AE      1
PP      1
RI      1
AJ      1
GA      1
Name: export_53, Length: 91, dtype: int64

#### Nombre d'article par langue de l'article

In [12]:
mentions

,mentions_0,mentions_1,mentions_2,mentions_3,mentions_4,mentions_5,mentions_6,mentions_7,mentions_8,mentions_9,mentions_10,mentions_11,mentions_12,mentions_13,mentions_14,mentions_15
0,410412347,20150218230000,20150218230000,1,dailymaverick.co.za,http://www.dailymaverick.co.za/article/2015-02...,19,-1,4594,4634,1,50,6665,-4.477612,NaN,NaN
1,410412348,20150218230000,20150218230000,1,indiatimes.com,http://timesofindia.indiatimes.com/city/bengal...,2,-1,300,344,1,50,2541,2.078522,NaN,NaN
2,410412349,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1297,1232,0,10,2576,7.517084,NaN,NaN
3,410412350,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1298,1233,1,20,2576,7.517084,NaN,NaN
4,410412351,20150218230000,20150218230000,1,eastidahonews.com,http://www.eastidahonews.com/2015/02/neil-patr...,1,-1,103,122,1,100,1432,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8457,410414615,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,442,0,20,1994,-3.703704,NaN,NaN
8458,410414616,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,367,0,20,1994,-3.703704,NaN,NaN
8459,410232648,20150218100000,20150218230000,1,suttonguardian.co.uk,http://www.suttonguardian.co.uk/news/national/...,6,1870,-1,1803,1,100,5040,-0.738916,NaN,NaN
8460,410339294,20150218171500,20150218230000,1,edgeboston.com,http://www.edgeboston.com/entertainment/celebr...,2,454,-1,411,1,50,858,6.250000,NaN,NaN
8461,410414617,20150218230000,20150218230000,1,bbg.gov,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...,1,318,-1,345,1,100,1584,-0.411523,NaN,NaN

In [13]:
# mentions_gkg_translation_joined = mentions + gkg_translation on "gkg_translation_3" (CommonSourceDomain)
# mentions_gkg_translation_export_joined = mentions_gkg_translation_joined + export on "export_0" (GlobalIdEvent)

mentions_gkg_translation_joined = mentions.merge(gkg_translation, left_on='mentions_4', right_on='gkg_translation_3')
mentions_gkg_translation_export_joined = mentions_gkg_translation_joined.merge(export, left_on='mentions_0', right_on='export_0')
mentions_gkg_translation_export_joined["gkg_translation_25"] = mentions_gkg_translation_export_joined["gkg_translation_25"].apply(lambda x : x.split(";")[0].split(":")[-1])

In [14]:
pd.DataFrame(mentions_gkg_translation_export_joined.gkg_translation_25.value_counts())

     gkg_translation_25
zho                1512
por                 184
hin                  64
ell                  40
spa                  33
ita                  18
deu                  10
tur                   8
fra                   3

### Pour un pays donné en paramètre, affichez les évènements qui y ont eu place triées par le nombre de mentions (tri décroissant); permettez une agrégation par jour/mois/année

In [15]:
def display_event(event_table, country, day, month, year):
    event_table[1] = pd.to_datetime(event_table["export_1"], format='%Y%m%d') # column_1 = Day 
    list_event = event_table.loc[event_table["export_53"] == country]
    list_event_sorted = list_event.sort_values(by="export_31") # column_31 = NumMentions
    #print(list_event_sorted)
    list_event_sorted['day'] = list_event_sorted[1].dt.day
    list_event_sorted['month'] = list_event_sorted[1].dt.month
    list_event_sorted['year'] = list_event_sorted[1].dt.year
    
    event_by_day_month_year = list_event_sorted.loc[(list_event_sorted.day == day) & (list_event_sorted.month == month) & (list_event_sorted.year == year)]
    event_by_month_year = list_event_sorted.loc[(list_event_sorted.month == month) & (list_event_sorted.year == year)]
    event_by_year = list_event_sorted.loc[list_event_sorted.year == year]
    #print(event_by_year)
    print("--- Events in " + str(day) + "/" + str(month) + "/" + str(year) +" ---\n")
    if event_by_day_month_year["export_0"].empty:
        print("0 events found")
    else:
        print(event_by_day_month_year["export_0"])
    print("\n\n--- Events in " + str(month) + "/" + str(year) +" ---\n")
    if event_by_month_year["export_0"].empty:
        print("0 events found")
    else:
        print(event_by_month_year["export_0"])
    print("\n\n--- Events in " + str(year) + " ---\n")
    if event_by_year["export_0"].empty:
        print("0 events found")
    else:
        print(event_by_year["export_0"])

display_event(export, "SW", 19, 1, 2015)

--- Events in 19/1/2015 ---

0 events found


--- Events in 1/2015 ---

0 events found


--- Events in 2015 ---

1833    410414180
2024    410414371
1694    410414041
Name: export_0, dtype: int64

In [16]:
gkg

,gkg_0,gkg_1,gkg_2,gkg_3,gkg_4,gkg_5,gkg_6,gkg_7,gkg_8,gkg_9,gkg_10,gkg_11,gkg_12,gkg_13,gkg_14,gkg_15,gkg_16,gkg_17,gkg_18,gkg_19,gkg_20,gkg_21,gkg_22,gkg_23,gkg_24,gkg_25,gkg_26
0,20150218230000-0,20150218230000,2,BBC Monitoring,as listed in Russian /BBC Monitoring/(c) BBC,"ARREST#400#political#4#Rossiya, Orenburgskaya ...","ARREST#400#political#4#Rossiya, Orenburgskaya ...",TERROR;REBELS;TAX_ETHNICITY;TAX_ETHNICITY_UKRA...,"TAX_FNCACT,2011;TAX_FNCACT,3449;TAX_FNCACT,381...","4#Budapest, Budapest, Hungary#RS#HU05#47.5#19....","4#Novorossiya, Primorskiy Kray, Russia#RS#RS59...",petro poroshenko;arkadiy dvorkovich;gen aleksa...,"Petro Poroshenko,2326;Arkadiy Dvorkovich,3483;...",gazprom,"Gazprom,666","-5.3475935828877,2.13903743315508,7.4866310160...",NaN,"wc:693,c1.1:1,c1.2:1,c12.1:43,c12.10:58,c12.11...",NaN,NaN,NaN,NaN,1332|134||prisoners are treated humanely ; the...,"Channel One,628;Channel One,755;Channel One,14...","3,channels,476;3,channels reported,824;1,corre...",NaN,NaN
1,20150218230000-1,20150218230000,2,BBC Monitoring,"Al-Sharq al-Awsat website, London/BBC Monitori...",NaN,NaN,TAX_FNCACT;TAX_FNCACT_ENVOY;TAX_ETHNICITY;TAX_...,"IDEOLOGY,6790;IDEOLOGY,10592;KILL,1960;KILL,13...",1#Qatar#SA#QA#25.5#51.25#QA;1#Syria#SA#SY#35#3...,1#Turks#SA#TU##39#35#TU#9059;1#Syrian#SA#SY##3...,al-arab kobane;emrullah isler;nasirite alawite...,"Al-Arab Kobane,4903;Emrullah Isler,77;Nasirite...",development party;united states,"Development Party,3577;Development Party,3746;...","-0.54054054054054,3.82239382239382,4.362934362...",NaN,"wc:2376,c1.2:1,c1.4:7,c12.1:163,c12.10:276,c12...",NaN,NaN,NaN,NaN,332|26||greatly complicate matters#4494|37||ma...,"Emrullah Isler,83;Arab Spring,3571;Development...","2,fronts at the political,1455;2,main strategi...",NaN,NaN
2,20150218230000-2,20150218230000,1,wjon.com,http://wjon.com/wjon-news-on-demand-wednesday-...,NaN,NaN,MANMADE_DISASTER;MANMADE_DISASTER_WITHOUT_POWE...,"MANMADE_DISASTER,91;POWER_OUTAGE,91;",NaN,NaN,NaN,NaN,NaN,NaN,"0,0,0,0,29.7029702970297,0.99009900990099,93",NaN,"wc:93,c12.1:7,c12.10:10,c12.12:5,c12.13:4,c12....",http://wac.450F.edgecastcdn.net/80450F/wjon.co...,http:/wac.450F.edgecastcdn.net/80450F/wjon.com...,NaN,https://youtube.com/channel/;https://youtube.c...,NaN,"Waite Park,125;City Food,233;Adobe Flash Playe...","500,people were without power,51;",NaN,NaN
3,20150218230000-3,20150218230000,1,wjol.com,http://www.wjol.com/common/more.php?m=15&r=3&i...,NaN,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_GOVERNOR;TAX_POLI...,"TAX_FNCACT,131;TAX_POLITICAL_PARTY,664;TAX_FNC...","2#Wisconsin, United States#US#USWI#44.2563#-89...","2#Wisconsin, United States#US#USWI##44.2563#-8...",michael madigan;rahm emanuel;jesus chuy garcia,"Michael Madigan,147;Rahm Emanuel,313;Jesus Chu...",NaN,NaN,"-4.58715596330275,1.8348623853211,6.4220183486...",NaN,"wc:103,c12.1:4,c12.10:13,c12.12:7,c12.13:6,c12...",NaN,NaN,NaN,NaN,NaN,"Governor Rauner,41;Speaker Michael Madigan,158...",NaN,NaN,NaN
4,20150218230000-4,20150218230000,1,straitstimes.com,http://www.straitstimes.com:80/news/world/unit...,NaN,NaN,DRONES;TAX_WORLDMAMMALS;TAX_WORLDMAMMALS_MICE;...,"TAX_FNCACT,634;TAX_FNCACT,1248;TAX_FNCACT,907;...","1#United States#US#US#38#-97#US;3#Miami, Flori...","3#Miami, Florida, United States#US#USFL#FL086#...",omid farokhzad,"Omid Farokhzad,885",columbia university medical centre;harvard med...,"Columbia University Medical Centre,680;Harvard...","-1.80505415162455,3.6101083032491,5.4151624548...",4#2#18#0#706,"wc:255,c12.1:10,c12.10:28,c12.12:11,c12.13:7,c...",http://www.straitstimes.com/sites/straitstimes...,NaN,NaN,NaN,NaN,"United States,583;Columbia University Medical ...","5,weeks,1194;",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,20150218230000-203,20150218230000,1,theaustralian.com.au,http://www.theaustralian.com.au/business/finan...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_CHIEF;TAX_FNCACT_EXECUTI...,"TAX_FNCACT,552;TAX_ETHNICITY,1171;TAX_ETHNICIT...",1#Australia#AS#AS#-27#133#AS,1#Australian#AS#AS##-27#133#AS#1171;1#Australi...,craig meller,"Craig Meller,575",NaN,NaN,"6.06060606060606,6.06060606060606,0,6.06060606...",4#12#31#0#17;4#4#10#0#253;4#3#3#0#297;1#0#0#20...,"wc:300,c1.2:7,c12.1:8,c12.10:23,c12.12:3,c12.1...",http://resources.news.com.au/cs/theaustralian/...,NaN,NaN,NaN,NaN,"Craig Meller,647;Dow Jones,1941","884000000,dollars ,65;672000000,dollars result...",NaN,NaN
3184,20150218230000-204,20150218230000,1,yahoo.com,http://finance.yahoo.com/news/chg-healthcare-s...,NaN,NaN,MEDICAL;TAX_WORLDLANGUAGES;TAX_WORLDLANGUAGES_...,"GENERAL_HEALTH,1512;TAX_FNCACT,1339;TAX_FNCACT...",1#United States#US#US#38#-97#US,1#America#US#US##38#-97#US#632;1#America#US#US...,scott beck,"Scott Beck,945",foundation medical staffing;healthcare services,"Foundation Medical Staffing,1521;Healthcare Se...","9.03225806451613,9.03225806451613,0,9.03225806...",4#2#18#0#36;1#0#0#1979#1351,"wc:278,c1.2:4,c12.1:21,c12.10:22,c12.12:4,c12....",http://l2.yimg.com/bt/api/res/1.2/6rik6AZwuPGC...,NaN,NaN,NaN,NaN,"Weatherby Healthcare,219;Staffing Award,378;No...","100,Best Places,1632;5,consecutive years,1656;",NaN,NaN
3185,20150218230000-205,20150218230000,1,france24.com,http://www.france24.com/en/20150218-un-issue-f...,KILL#200##1#Liberia#LI#LI#6.5#-9.5#LI;,KILL#200##1#Liberia#LI#LI#6.5#-9.5#LI#1821;,TAX_DISEASE;TAX_DISEASE_EBOLA;TAX_WORLDFISH;TA...,"GENERAL_HEALTH,1311;MEDICAL,1311;TAX_DISEASE,1...","1#Guinea#LI#GV#11#-10#GV;4#Freetown, Western A...",1#Sierra Leone#LI#SL##8.5#-11.5#SL#179;1#Sierr...,david nabarro;laura taylor-pearce,"David Nabarro,482",united nations,"United Nations,15;United Nations,54;United Nat...","-3.63636363636364,1.81818181818182,5.454545454...",NaN,"wc:307,c12.1:17,c12.10:30,c12.12:12,c12.13:14,...",http://scd.france24.com/en/files/imagecache/fr...,NaN,NaN,NaN,NaN,"United Nations,44;Sierra Leone,175;David Nabar...","3000000,dollars donated,180;31,donors since Se...",NaN,NaN
3186,20150218230000-206,20150218230000,1,rri.ro,http://www.rri.ro/en_gb/RadioRomaniaInternatio...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_AUTHOR;MEDIA_MSM;TAX_FNC...,"TAX_FNCACT,13378;MEDIA_MSM,478;MEDIA_MSM,1389;...",NaN,NaN,categorytype parentcategory,"Categorytype Parentcategory,12207;Categorytype...",group by page,"Group By Page,11360","-0.679941719281204,0,0.679941719281204,0.67994...",NaN,"wc:1695,c12.1:40,c12.10:54,c12.12:15,c12.13:1,...",NaN,NaN,NaN,https://youtube.com/user/EugenCojocariu?featur...,NaN,"History Show,15982;CategoryType ParentCategory...","15,SELECT `Page` `id`,956;15,SELECT `Page` `id...",NaN,NaN
3187,20150218230000-207,20150218230000,1,sfgate.com,http://www.sfgate.com/business/article/Swiss-p...,NaN,NaN,TRIAL;TAX_FNCACT;TAX_FNCACT_PROSECUTORS;DRUG_T...,"TAX_ETHNICITY,1135;TAX_ETHNICITY,1236;TAX_WORL...","4#Geneva, Genè, Switzerland#SZ#SZ07#46.1956#6....",1#French#SZ#FR##46#2#FR#1135;1#French#SZ#FR##4...,herve falciani,"Herve Falciani,1109",bank suisse;international consortium of invest...,"Bank Suisse,296;International Consortium Of In...","-3.40136054421769,0.680272108843537,4.08163265...",1#0#0#2007#1001;1#0#0#2008#1209;1#0#0#2012#156...,"wc:265,c12.1:8,c12.10:11,c12.12:5,c12.13:4,c12...",http://www.sfgate.com/img/pages/article/opengr...,NaN,NaN,NaN,591|29||the recent public revelations,"International Consortium,791;Investigative Jou...","1000000,of dollars for drug,152;1000000,of dol...",NaN,NaN

### Pour une source de donnés passée en paramètre (gkg.SourceCommonName) affichez les thèmes, personnes, lieux dont les articles de cette sources parlent ainsi que le nombre d’articles et le ton moyen des articles (pour chaque thème/personne/lieu); permettez une agrégation par jour/mois/année.

In [17]:
from statistics import mean

def source_stats(gkg_table, source, day=None, month=None, year=None):
#     # column_3 = SourceCommonName
#     # column_7 = Theme
#     # column_11 = Person
#     # column_9 = Locations
#     # column_15 = Avg_Tone
#     gkg_table[1] = pd.to_datetime(gkg_table[1], format='%Y%m%d%H%M%S') # column_1 = Day 
#     list_event = gkg_table.loc[event_table[3] == source]
#     list_theme = list_event.loc(list_event)
    

    themes = list()
    persons = list()
    locations = list()

    df_avg_tone_theme = dict()
    df_avg_tone_person = dict()
    df_avg_tone_location = dict()

    gkg_table["gkg_1"] = pd.to_datetime(gkg_table["gkg_1"], format='%Y%m%d%H%M%S') # column_1 = Day 
    list_event = gkg_table.loc[gkg_table["gkg_3"] == source]
    list_theme = list_event["gkg_7"].tolist()
    list_person = list_event["gkg_11"].tolist()
    list_location = list_event["gkg_9"].tolist()

    # THEME
    list_theme = [t for t in list_theme if str(t) != 'nan'] # drop nan values
    for theme in list_theme:
        theme_temp_list = str(theme).split(";")
        theme_temp_list.pop() # drop the last element of the list which is an empty string
        for theme_sub in theme_temp_list:
            themes.append(theme_sub)
    themes = list(dict.fromkeys(themes)) # drop duplicated themes

    # PERSON
    list_person = [l for l in list_person if str(l) != 'nan'] # drop nan values
    for person in list_person:
        person_temp_list = str(person).split(";")
        for person_sub in person_temp_list:
            persons.append(person_sub)
    persons = list(dict.fromkeys(persons)) # drop duplicated themes

    # LOCATION
    list_location = [l for l in list_location if str(l) != 'nan'] # drop nan values
    for location in list_location:
        location_temp_list = str(location).split("#")
        locations.append(location_temp_list[1])
    locations = list(dict.fromkeys(locations)) # drop duplicated themes
    
    print("---- SOURCE = " + source + "----\n")
    
    print("\n---- THEMES ----\n")
    print(themes)
    print("\n\n---- PERSONS ----\n")
    print(persons)
    print("\n\n---- LOCATIONS ----\n")
    print(locations)

    # TONE AVG PER THEMES
    for theme in themes:
        list_theme_ = list_event["gkg_7"].astype(str)
        list_theme_ = list_theme_[list_theme_.str.contains(theme)]
        idx_theme = list_theme_.index.tolist()
        avg_tone_theme = list()
        for i in idx_theme:
            avg_temp = gkg["gkg_15"][i].split(",")[0]
            avg_tone_theme.append(float(avg_temp))

        avg_tone_theme = mean(avg_tone_theme)
        df_avg_tone_theme[theme] = avg_tone_theme
    df_avg_tone_theme = pd.DataFrame(df_avg_tone_theme.items(), columns=['Themes', 'AVG_Tone'])

    # TONE AVG PER PERSON
    for person in persons:
        list_person_ = list_event["gkg_11"].astype(str)
        list_person_ = list_person_[list_person_.str.contains(person)]
        idx_person = list_person_.index.tolist()
        avg_tone_person = list()
        for i in idx_person:
            avg_temp_person = gkg["gkg_15"][i].split(",")[0]
            avg_tone_person.append(float(avg_temp_person))

        avg_tone_person = mean(avg_tone_person)
        df_avg_tone_person[person] = avg_tone_person
    df_avg_tone_person = pd.DataFrame(df_avg_tone_person.items(), columns=['Persons', 'AVG_Tone'])
    df_avg_tone_person

    # TONE AVG PER LOCATION
    for location in locations:
        list_location_ = list_event["gkg_9"].astype(str)
        list_location_ = list_location_[list_location_.str.contains(location)]
        idx_location = list_location_.index.tolist()
        avg_tone_location = list()
        for i in idx_location:
            avg_temp_location = gkg["gkg_15"][i].split(",")[0]
            avg_tone_location.append(float(avg_temp_location))

        avg_tone_location = mean(avg_tone_location)
        df_avg_tone_location[location] = avg_tone_location
    df_avg_tone_location = pd.DataFrame(df_avg_tone_location.items(), columns=['Locations', 'AVG_Tone'])
    
    print("\n\n\n\n---- AVG TONE PER THEMES ----\n")
    print(df_avg_tone_theme)
    print("\n\n---- AVG TONE PER PERSONS ----\n")
    print(df_avg_tone_person)
    print("\n\n---- AVG TONE PER LOCATIONS ----\n")
    print(df_avg_tone_location)
    
source_stats(gkg, "wjon.com")

---- SOURCE = wjon.com----


---- THEMES ----

['MANMADE_DISASTER', 'MANMADE_DISASTER_WITHOUT_POWER', 'POWER_OUTAGE', 'TAX_POLITICAL_PARTY', 'TAX_POLITICAL_PARTY_DEMOCRATS', 'TAX_FNCACT', 'TAX_FNCACT_WORKERS', 'TAX_FNCACT_WORKER', 'TAX_FNCACT_EMPLOYEE', 'TAX_ETHNICITY', 'TAX_ETHNICITY_AMERICANS', 'TAX_POLITICAL_PARTY_DEMOCRAT', 'TAX_POLITICAL_PARTY_REPUBLICAN', 'LEADER', 'TAX_FNCACT_LAWMAKERS', 'TAX_FNCACT_MANAGER', 'TAX_FNCACT_GENERAL_MANAGER', 'TAX_FNCACT_OFFICIALS', 'MEDIA_MSM', 'TAX_FNCACT_CHILD', 'ACT_MAKESTATEMENT', 'EDUCATION', 'TAKE_OFFICE', 'TAX_FNCACT_MAYOR', 'TAX_FNCACT_DIRECTOR', 'TAX_FNCACT_FINANCE_DIRECTOR', 'TAX_FNCACT_ADMINISTRATOR', 'ELECTION', 'MANMADE_DISASTER_IMPLIED', 'AVIATION_INCIDENT', 'AVIATION_INCIDENT_PLANE_CRASHED', 'KILL', 'TAX_FNCACT_PILOT', 'TAX_ETHNICITY_GERMAN', 'TAX_WORLDLANGUAGES', 'TAX_WORLDLANGUAGES_GERMAN', 'TAX_FNCACT_STUDENT', 'TAX_FNCACT_MAN', 'TAX_FNCACT_SPEAKER', 'TAX_FNCACT_LEADER', 'TAX_FNCACT_MAJORITY_LEADER', 'TAX_FNCACT_COMMISSIONER', 'LEGISLATION', 'NEGOTIATIONS', 'DELAY', 'GENERAL_HEALTH', 'MEDICAL', 'SOC_POINTSOFINTEREST', 'SOC_POINTSOFINTEREST_HOSPITAL']


---- PERSONS ----

['ryan winkler', 'rick spielman', 'adrian peterson', 'dan debaun', 'bruce hentges', 'jim aleshire', 'rick miller', 'alex svejkovsky', 'dave bentrud', 'kris dokendorf', 'paul hetland', 'bob thelen', 'kris moran', 'scott olson', 'alexander voigt', 'hannah foslien', 'mark dayton', 'kurt daudt']


---- LOCATIONS ----

['Minnesota, United States', 'Germany']




---- AVG TONE PER THEMES ----

                             Themes  AVG_Tone
0                  MANMADE_DISASTER -2.031863
1    MANMADE_DISASTER_WITHOUT_POWER -1.639344
2                      POWER_OUTAGE -1.639344
3               TAX_POLITICAL_PARTY  0.529534
4     TAX_POLITICAL_PARTY_DEMOCRATS  3.875969
5                        TAX_FNCACT -0.650074
6                TAX_FNCACT_WORKERS  3.875969
7                 TAX_FNCACT_WORKER  3.875969
8               TAX_FNCACT_EMPLOYEE  3.875969
9                     TAX_ETHNICITY  0.529534
10          TAX_ETHNICITY_AMERICANS  3.875969
11     TAX_POLITICAL_PARTY_DEMOCRAT  3.875969
12   TAX_POLITICAL_PARTY_REPUBLICAN  0.529534
13                           LEADER  0.353023
14             TAX_FNCACT_LAWMAKERS  0.529534
15               TAX_FNCACT_MANAGER -1.492537
16       TAX_FNCACT_GENERAL_MANAGER -1.492537
17             TAX_FNCACT_OFFICIALS -1.492537
18                        MEDIA_MSM -1.492537
19                 TAX_FNCACT_CHILD -1.492537
20                ACT_MAKESTATEMENT -1.492537
21                        EDUCATION  2.173913
22                      TAKE_OFFICE  0.000000
23                 TAX_FNCACT_MAYOR  0.000000
24              TAX_FNCACT_DIRECTOR  0.000000
25      TAX_FNCACT_FINANCE_DIRECTOR  0.000000
26         TAX_FNCACT_ADMINISTRATOR  0.000000
27                         ELECTION  0.000000
28         MANMADE_DISASTER_IMPLIED -2.816901
29                AVIATION_INCIDENT -2.816901
30  AVIATION_INCIDENT_PLANE_CRASHED -2.816901
31                             KILL -2.816901
32                 TAX_FNCACT_PILOT -2.816901
33             TAX_ETHNICITY_GERMAN -2.816901
34               TAX_WORLDLANGUAGES -2.816901
35        TAX_WORLDLANGUAGES_GERMAN -2.816901
36               TAX_FNCACT_STUDENT -2.816901
37                   TAX_FNCACT_MAN -2.154719
38               TAX_FNCACT_SPEAKER -2.816901
39                TAX_FNCACT_LEADER -2.816901
40       TAX_FNCACT_MAJORITY_LEADER -2.816901
41          TAX_FNCACT_COMMISSIONER -2.816901
42                      LEGISLATION -2.816901
43                     NEGOTIATIONS -2.816901
44                            DELAY -2.816901
45                   GENERAL_HEALTH -2.816901
46                          MEDICAL -2.816901
47             SOC_POINTSOFINTEREST -2.816901
48    SOC_POINTSOFINTEREST_HOSPITAL -2.816901


---- AVG TONE PER PERSONS ----

            Persons  AVG_Tone
0      ryan winkler  3.875969
1     rick spielman -1.492537
2   adrian peterson -1.492537
3        dan debaun  1.086957
4     bruce hentges  2.173913
5      jim aleshire  0.675676
6       rick miller  0.675676
7   alex svejkovsky  0.675676
8      dave bentrud  0.675676
9    kris dokendorf  0.000000
10     paul hetland  0.000000
11       bob thelen  0.000000
12       kris moran -2.816901
13      scott olson -2.816901
14  alexander voigt -2.816901
15   hannah foslien -2.816901
16      mark dayton -2.816901
17       kurt daudt -2.816901


---- AVG TONE PER LOCATIONS ----

                  Locations  AVG_Tone
0  Minnesota, United States  1.191716
1                   Germany -2.816901

### Etudier l’évolution des relations entre deux pays (specifies en paramètre) au cours de l’année. Vous pouvez vous baser sur la langue de l’article, le ton moyen des articles, les themes plus souvent citées, les personalités ou tout element qui vous semble pertinent.

In [18]:
### Resemble à la requête d'avant